enum Pergunta1 {um, dois}
enum Pergunta2 {um, dois}
enum Pergunta3 {um, dois}
enum Pergunta4 {um, dois}
enum Pergunta5 {um, dois}
enum Pergunta6 {um, dois}
enum Pergunta7 {um, dois}
enum Pergunta8 {um, dois}
enum Pergunta9 {um, dois}
enum Pergunta10 {um, dois}